# Generated by Django 6.0.6 on 2026-06-25 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='name (English)')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in filter menus.', verbose_name='display order')),
            ],
            options={
                'verbose_name': 'restaurant category',
                'verbose_name_plural': 'restaurant categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=50, unique=True, verbose_name='name (English)')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=255, verbose_name='name (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
                ('address_ar', models.CharField(max_length=500, verbose_name='address (Arabic)')),
                ('address_en', models.CharField(max_length=500, verbose_name='address (English)')),
                ('city', models.CharField(choices=[('jerusalem', 'Jerusalem'), ('al_ram', 'Al-Ram'), ('beit_hanina', 'Beit Hanina'), ('al_eizariya', 'Al-Eizariya'), ('abu_dis', 'Abu Dis'), ('kafr_aqab', 'Kafr Aqab'), ('ramallah', 'Ramallah'), ('al_bireh', 'Al-Bireh'), ('birzeit', 'Birzeit'), ('silwad', 'Silwad'), ('beit_rima', 'Beit Rima'), ('deir_dibwan', 'Deir Dibwan'), ('beit_sira', 'Beit Sira'), ('jericho', 'Jericho'), ('al_auja', 'Al-Auja'), ('bethlehem', 'Bethlehem'), ('beit_jala', 'Beit Jala'), ('beit_sahour', 'Beit Sahour'), ('beit_fajjar', 'Beit Fajjar'), ('husan', 'Husan'), ('nahalin', 'Nahalin'), ('hebron', 'Hebron'), ('yatta', 'Yatta'), ('dura', 'Dura'), ('halhul', 'Halhul'), ('idhna', 'Idhna'), ('tarqumiyya', 'Tarqumiyya'), ('surif', 'Surif'), ('sair', "Sa'ir"), ('beit_ummar', 'Beit Ummar'), ('dhahriya', 'Ad-Dhahriya'), ('nablus', 'Nablus'), ('sebastia', 'Sebastia'), ('beit_furik', 'Beit Furik'), ('beita', 'Beita'), ('aqraba', 'Aqraba'), ('jenin', 'Jenin'), ('qabatiya', 'Qabatiya'), ('yabad', "Ya'bad"), ('arraba', 'Arraba'), ('burqin', 'Burqin'), ('tubas', 'Tubas'), ('tamoun', 'Tamoun'), ('tulkarm', 'Tulkarm'), ('anabta', 'Anabta'), ('beit_iba', 'Beit Iba'), ('qalqilya', 'Qalqilya'), ('azzun', 'Azzun'), ('kafr_thulth', 'Kafr Thulth'), ('salfit', 'Salfit'), ('haris', 'Haris'), ('kafr_al_dik', 'Kafr ad-Dik'), ('jabalia', 'Jabalia'), ('beit_lahiya', 'Beit Lahiya'), ('beit_hanoun', 'Beit Hanoun'), ('gaza', 'Gaza City'), ('nuseirat', 'Nuseirat'), ('bureij', 'Bureij'), ('maghazi', 'Maghazi'), ('deir_al_balah', 'Deir al-Balah'), ('khan_yunis', 'Khan Yunis'), ('abasan', 'Abasan'), ('bani_suheila', 'Bani Suheila'), ('khuza_a', "Khuza'a"), ('rafah', 'Rafah'), ('tel_al_sultan', 'Tel al-Sultan')], db_index=True, max_length=30, verbose_name='city')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate (e.g. 31.900000).', max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate (e.g. 35.200000).', max_digits=9, null=True, verbose_name='longitude')),
                ('working_hours_ar', models.CharField(blank=True, help_text='e.g. الأحد–الخميس: 9ص–10م', max_length=255, verbose_name='working hours (Arabic)')),
                ('working_hours_en', models.CharField(blank=True, help_text='e.g. Sun–Thu: 9 AM–10 PM', max_length=255, verbose_name='working hours (English)')),
                ('is_open', models.BooleanField(db_index=True, default=True, help_text='Toggle to mark the restaurant as temporarily closed. Displayed as the green/grey Open/Closed badge on listing cards.', verbose_name='is open')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Admin-controlled approval status of this listing.', max_length=10, verbose_name='status')),
                ('price_range', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Budget (₪)'), (2, 'Moderate (₪₪)'), (3, 'Expensive (₪₪₪)')], help_text='Rough price indicator shown as bar icons on listing cards.', null=True, verbose_name='price range')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(blank=True, help_text='The restaurant-owner account that manages this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('category', models.ForeignKey(blank=True, help_text='Cuisine / restaurant type shown on listing cards.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='restaurants.restaurantcategory', verbose_name='category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Searchable keywords displayed under the restaurant card.', related_name='restaurants', to='restaurants.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=150, verbose_name='name (English)')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the menu.', verbose_name='display order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'menu category',
                'verbose_name_plural': 'menu categories',
                'ordering': ['order', 'name_en'],
                'unique_together': {('restaurant', 'name_en')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(max_length=255, verbose_name='name (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='description (English)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in ILS (₪).', max_digits=8, verbose_name='price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/', verbose_name='image')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this item without deleting it.', verbose_name='is available')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first within the category.', verbose_name='display order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.menucategory', verbose_name='category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['order', 'name_en'],
                'indexes': [models.Index(fields=['restaurant', 'is_available'], name='restaurants_restaur_1087ee_idx'), models.Index(fields=['category', 'order'], name='restaurants_categor_fddf31_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/images/', verbose_name='image')),
                ('image_type', models.CharField(choices=[('cover', 'Cover Photo'), ('profile', 'Profile / Logo'), ('gallery', 'Gallery')], db_index=True, default='gallery', max_length=10, verbose_name='image type')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Mark this image as the featured photo shown on listing cards. Only one image per restaurant can be primary.', verbose_name='is primary')),
                ('caption_ar', models.CharField(blank=True, max_length=255, verbose_name='caption (Arabic)')),
                ('caption_en', models.CharField(blank=True, max_length=255, verbose_name='caption (English)')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the gallery.', verbose_name='display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurants.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'restaurant image',
                'verbose_name_plural': 'restaurant images',
                'ordering': ['-is_primary', 'order', 'uploaded_at'],
                'indexes': [models.Index(fields=['restaurant', 'is_primary'], name='restaurants_restaur_04b7e6_idx'), models.Index(fields=['restaurant', 'image_type'], name='restaurants_restaur_ad8161_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city', 'status'], name='restaurants_city_0ed071_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status', 'is_open'], name='restaurants_status_0104b6_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status', 'created_at'], name='restaurants_status_773e15_idx'),
        ),
    ]
