# Generated by Django 6.0.6 on 2026-06-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_approved'),
        ('accounts', '0002_customuser_phone'),
    ]

    operations = [
    ]
