# Generated by Django 6.0.6 on 2026-06-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20260628_1437'),
        ('accounts', '0003_merge_20260628_1842'),
    ]

    operations = [
    ]
