# Generated by Django 6.0.6 on 2026-07-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_city_address'),
        ('accounts', '0004_merge_20260628_2013'),
    ]

    operations = [
    ]
