# Generated by Django 6.0.6 on 2026-06-25 12:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating from 1 (worst) to 5 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(help_text='Written feedback about the restaurant.', verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant', verbose_name='restaurant')),
                ('user', models.ForeignKey(blank=True, help_text='The user who wrote this review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(verbose_name='reply text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, help_text='The user (owner or regular) who posted this reply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_replies', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='reviews.review', verbose_name='review')),
            ],
            options={
                'verbose_name': 'comment reply',
                'verbose_name_plural': 'comment replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/images/', verbose_name='image')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the review image gallery.', verbose_name='display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='review')),
            ],
            options={
                'verbose_name': 'review image',
                'verbose_name_plural': 'review images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='saved at')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='restaurants.restaurant', verbose_name='restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'wishlist entry',
                'verbose_name_plural': 'wishlist entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_review', 'New Review'), ('new_reply', 'New Reply'), ('status_change', 'Status Change'), ('general', 'General')], db_index=True, default='general', max_length=20, verbose_name='type')),
                ('text_ar', models.TextField(help_text='Notification message displayed to Arabic-language users.', verbose_name='text (Arabic)')),
                ('text_en', models.TextField(help_text='Notification message displayed to English-language users.', verbose_name='text (English)')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='reviews_not_user_id_cfcdb5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['restaurant', 'rating'], name='reviews_rev_restaur_b8125a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['restaurant', 'created_at'], name='reviews_rev_restaur_f1010e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'restaurant')},
        ),
    ]
