# Generated by Django 6.0.6 on 2026-06-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-is_reported', '-created_at'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='is_reported',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged by users for admin moderation.', verbose_name='is reported'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this review from the public site.', verbose_name='is visible'),
        ),
    ]
